### ISSUE TITLE
Simulator does not have correct sensor locations 

### ISSUE THREAD

**Issue by ironmig** [uf-mil/Navigator#112]
One thing holding me back from making serious use out of the simulator has been apparent differences between the location of sensors on Navigator in gazebo and the transformations publishes by tf.launch. Rather then trying to get these numbers just right, perhaps the simulator should just publish it's own TF's based on the boat model. A quick Google seems to show that this may even be the default behavior of a ros-ified gazebo.

**Comment by ironmig** [comment]
http://wiki.ros.org/gazebo2rviz

**Comment by whispercoros** [comment]
I was under the assumption that the locations of the simulated sensors as well as the TFs for the whole system were changed when Lucas measured everything. Was this not the case? Regardless, I think it is a worthwhile investment to have the sensors line up as close as possible to real life in the simulator, so I will look into this during the week.

**Comment by viron11111** [comment]
Anthony,

It's been almost a week.  Have you found a button (from Amazon) for the 
2nd computer yet?

-Andy

**Comment by ironmig** [comment]
From looking at how Sub8 did it, the problem is that our tf.launch specifies sensor locations in reference to measurement and gazebo is with reference to base_frame. I wrote a script to generate the correct values and will submit a PR with the fixes today after testing.

**Comment by whispercoros** [comment]
I am interested to see if this works, have you tested it? I believe the model of our boat has it's base_frame point at measurement. You should be able to check this in the simulator fairly easily.

**Comment by ironmig** [comment]
Tried to figure this out, could not. This is pretty high priority, as nothing really works without good TF's.

**Comment by whispercoros** [comment]
@ironmig When you were troubleshooting, was the issue with the position or rotation of the sensors?

**Comment by ironmig** [comment]
Hard to tell. Getting the rotation to be the same as the tf.launch is tough because cameras have their axises switched in tf but use the normal axises in gazebo. Might also have something to do with camera projection. A good first step is to finish that program Matt and I were working on to convert tf to sdf <pose> tags.

**Comment by whispercoros** [comment]
Is this program on upstream or one of the workstations?

**Comment by ironmig** [comment]
Fixed in #127
