### ISSUE TITLE
Simulator identify & dock model is inaccurate

### ISSUE THREAD

**Issue by ironmig** [uf-mil/Navigator#115]
Considering we will have almost no testing with the identify and dock challenge before hawaii, we really need a good model for the sim. Right now the displayed symbols are too dark (like detect deliver used to be). The model should be fixed and make it easy to change which symbols are present

**Comment by whispercoros** [comment]
I believe Lucas has completed replacement models; I will put those in the simulator once I edit the coloring on them.

**Comment by whispercoros** [comment]
The models have been updated on my fork and will be in my next Simulator PR. I will also be making the dock pieces a solid object so that it is easier to move around. The panels can all be swapped out by editing the launch file.

**Comment by whispercoros** [comment]
This is fixed in #128.
