### ISSUE TITLE
Navigator singelton should have methods for setting mission parameters

### ISSUE THREAD

**Issue by ironmig** [uf-mil/Navigator#117]
It would be nice if mission-specific parameters could be set through the navigator singleton with methods similar to what we have implemented the vision services. A yaml file would list all the mission parameters and their valid values. 

Ex:
```
detect_deliver_shape:
  param: /mission/detect_deliver/Color
  args: ['GREEN','BLUE','RED']
```

Then in a mission (like scan the code):

```
if scan_the_code_color[2] == "RED"
  #Throws error if color is invalid, warnings if already set, etc
  navigator.set_mission_param('detect_deliver_shape','RED')

```

I'll work on this. Not sure how this will work into mission planer system...

**Comment by mattlangford** [comment]
You have the power
But I will do it if you'd like
