### ISSUE TITLE
Simulator launching problems

### ISSUE THREAD

**Issue by ironmig** [uf-mil/Navigator#121]
There seems to still be some frustrating problems trying to launch the sim.  It is probably a matter of timing. Sometimes gazebo will just freeze on a black screen, sometimes gazebo doesn't come up at all. Sometimes it freezes in spawning models. Happens on slow computers and fast computers

Don't really have a more detailed bug report. Just launch it a couple times in a row and you’ll see some issues.

Seems like it is mostly is gazebo crashing, which freezes everything else up.

**Comment by mattlangford** [comment]
Try echoing some of the topics (`/odom`, `/velodyne_points`, `/stereo/left/image_raw`) to see if the backend is coming up and it's just the front end crashing. We've had this problem with the sub too, I guess it could be something not starting up at the right time.

**Comment by ironmig** [comment]
Correct, it is mostly a problem with just the front end when using sandbox mode. Perhaps there needs to be a delay / wait to allow gazebo to load before loading models. There are also various other synchronization issues like launching obstacle detection before bounds have been set.

**Comment by ironmig** [comment]
Maybe simulator.launch just shouldn't launch the gazebo client. Add in the readme somewhere how to launch the client separately (once simulator.launch is done)

**Comment by whispercoros** [comment]
I have been working on the simulator sporadically over the past week and the only time I have ever experienced a crash on launch is when the models from Git LFS were not up to date. I should point out that I only ever use shuttle or johnny-five for testing, though.

**Comment by whispercoros** [comment]
We have had a ton of issues attempting to sever the frontend from the backend in the past. Though it's supposed to be possible, and was even the plan for shuttle and johnny-five (headless gazebo servers that we connect to with the GUI), nobody was able to get it working.

**Comment by whispercoros** [comment]
Is there a specific out-of-order launching issue you have experienced, or do these happen at random? If it is a specific issue, we could move some things around in the launch file to try to get the ordering right.

**Comment by ironmig** [comment]
I think my issues were mostly from gzclient, which can be not run with the ``gui:=false``` argument.
