### ISSUE TITLE
RobotX write up

### ISSUE THREAD

**Issue by viron11111** [uf-mil/Navigator#126]
Missing write up on simulator, acoustic based transit, and stereo vision.

**Comment by whispercoros** [comment]
The simulator write up has been submitted.

**Comment by viron11111** [comment]
Roger.  Stereo vision, acoustic based transit, and the state machine write ups are the only missing portions from the software team.

**Comment by tessbianchi** [comment]
Who is doing the state machine?

**Comment by viron11111** [comment]
I wanted Matt to do it but he said you may be working on it already.  I assumed that we had a section for missions but it's not on the Google doc.  Tess, can you knock it out?  Just a quarter page on how our missions transition (txros stuff) with time outs ect...

**Comment by viron11111** [comment]
Have received write ups on stereo and acoustic based transit.  Last is the state machine.

**Comment by whispercoros** [comment]
@viron11111, can this be closed now that the paper deadline has passed?

**Comment by viron11111** [comment]
Still waiting on machine.  Tess said she would complete it on Tuesday.  Cutting it close!

**Comment by viron11111** [comment]
90% written as of this morning.  Missing electrical section, state machine write up, CAD model.
