### ISSUE TITLE
Write coral survey perception and mission

### ISSUE THREAD

**Issue by ironmig** [uf-mil/Navigator#132]
So far, no work has been done to write the perception or mission for the Underwater Shape Identification (previously Coral Survey) challenge. By the competition, we should have the mission written and the best perception we can get based on the sim, [the footage in hawaii](https://www.youtube.com/watch?v=JDpB1n8pPfs), and potential testing in a pool.

**Comment by whispercoros** [comment]
@DSsoto is working on the perception this week and I will be writing the actual mission seeing as not much progress has been made here. We hope to have a preliminary version tested in the simulator before Saturday (11/19/16).

**Comment by tessbianchi** [comment]
Once again, please do not split missions.

**Comment by DSsoto** [comment]
@tessbianchi, I disagree. You could argue that ultimately there should be only one person responsible for a mission  once we get to Hawaii, but in the meantime, teamwork and parallel development lets us get stuff done more quickly.

**Comment by ironmig** [comment]
#172 adds some work towards perception, though right now it does not have an interface to ros. @whispercoros what is the status of the mission code?
