### ISSUE TITLE
Downward looking camera

### ISSUE THREAD

**Issue by viron11111** [uf-mil/Navigator#136]
Need TF for downward looking camera.  Camera will be mounted on 2x4 cross beam at a depth less than 1 meter.  Lucas has been notified.  Has anyone done the camera calibration for the camera?  The camera is in 121 on the file cabinet next to the window.

**Comment by whispercoros** [comment]
@RustyBamboo is attempting to calibrate it at some point in the week, but @rleyva should be available on Thursday if he does not get it done by then.

**Comment by RustyBamboo** [comment]
Udev wasn't working for me... Messed around with launch files. Coriander, camera1394 weren't working. Need help calibrating @rleyva

**Comment by whispercoros** [comment]
Is this camera set up, or are we still waiting on it?

**Comment by viron11111** [comment]
It's a Point Grey Firefly, USB 2.0.  Ralph has worked with this before.  Check with Lucas to see if the camera is physically mounted yet.  South Korea has already made progress towards underwater identification:
https://www.youtube.com/watch?v=aNcCalUy1_w

It's getting real!!!

**Comment by RustyBamboo** [comment]
Solved in PR #154
