### ISSUE TITLE
Let's put LQRRT in the launch file

### ISSUE THREAD

**Issue by tessbianchi** [uf-mil/Navigator#152]

**Comment by mattlangford** [comment]
Examining potential issues (which we did multiple times today) is impossible if it's launched with the rest of the boat

**Comment by tessbianchi** [comment]
Oh should I close this then? 

Never gonna happen?

**Comment by whispercoros** [comment]
I think it should be in the gnc launch file, but commited in a commented out state. This will allow us to still debug during testing while also making it easy to get it to launch with the boat once we get to Hawaii.

**Comment by mattlangford** [comment]
I'd feel more comfortable just always launching it by itself even for competition.

**Comment by tessbianchi** [comment]
Okee doke, closing it.
