### ISSUE TITLE
Green/Blue confusion in DD/Docking Perception

### ISSUE THREAD

**Issue by ironmig** [uf-mil/Navigator#156]
In non ideal (very bright or very dim) lighting conditions, the color recognition for Detect Deliver / Docking perception confuses blue and green. I'm currently just looking at Hue to identify color. I believe @mattlangford is having the same problems with classifying buoy colors. Let's talk about how we can improve that with hardware or software changes. This could be a real problem in Hawaii.

**Comment by mattlangford** [comment]
Structured heat.

**Comment by whispercoros** [comment]
Clouds.
