### ISSUE TITLE
Classification Smearing

### ISSUE THREAD

**Issue by ironmig** [uf-mil/Navigator#163]
One potential improvement to the smearing could be synchronizing your tf. To do that:

Declare this outside of your callback, initialize in main function so that buffer is continuously updated with latest tf.

```
tf2_ros::Buffer tfBuffer;
TransformListener tfListener(tfBuffer, nh);
```

Then in your velodyne callback
```
//Duration is how long to block to wait for tf
  if (!tfBuffer.canTransform("enu", "velodyne",pcloud->header.stamp,  ros::Duration(1)))
  {
//Do something if tf can't happen
  }
  geometry_msgs::TransformStamped transform = tfBuffer.lookupTransform("enu", "velodyne", pcloud->header.stamp);
```
This ensures that your tf is synchronized to the time the pointcloud was produced.

**Comment by maverick7170** [comment]
Thanks for looking into this! These changes didn't make a difference in my bag data but it's probably possible that it may matter at some point, so I'll leave the changes in.

**Comment by tessbianchi** [comment]
It seems like close to nothing can be done for this problem, aside from going back in time and properly calibrating the lidar. 

I have write the image segmentation layer to object classification. This is a solution to the classification problems that we are having. Can I close this?

**Comment by mgriessler** [comment]
I suggest we clone this issue to MIL's time machine project.
