### ISSUE TITLE
Tf_fudger replaces wrong line

### ISSUE THREAD

**Issue by DSsoto** [uf-mil/Navigator#183]
If you call tf_fudger with a new transform and it shares a frame_id with one of the transforms already in tf.launch, it will replace that line instead of adding a new one.
![image](https://cloud.githubusercontent.com/assets/8714358/21220132/92a08118-c25b-11e6-9a48-99cf0cb7b6cd.png)

**Comment by whispercoros** [comment]
Still broken, but OCD dictates we end on a clean repository.
