### ISSUE TITLE
Basic SIM integration test

### ISSUE THREAD

**Issue by ironmig** [uf-mil/NaviGator#204]
We should have a test to verify that the simulator works in a basic sense (without crashing, plugins missing, etc)

A nice integration test to do this is as follows:
* In a rostest, launch the gazebo simulator
* Simply verify that basic topics are received: odom, absodom, camera, lidar points
* Do some basic verification of these topic's data (odom starts at 0, camera images are non-empty, lidar points are non-empty)

The following stretch goals would test a lot of the functionality of the SIM and some of our other software stacks:
* Execute move command(s) in SIM (forward, backward, left, right, yaw), verify that when the move is complete Navigator is now at the correct position/orientation

**Comment by jmmarotta** [comment]
All goals except for the stretch goals are complete.

**Comment by ironmig** [comment]
#241
