### ISSUE TITLE
Find all python files (even ones that don't end in .py)

### ISSUE THREAD

**Issue by ironmig** [uf-mil/NaviGator#269]
For format checking and other purposes, we need a script that will print a list of all python files in a directory (recursively down subdirectories too). Right now we just run find piped into grep for .py, but some python files are scripts that don't end in .py. 

Print all files that EITHER
* end in .py
* have ```#!/usr/bin/env python``` as the first line

**Comment by brooksturtle** [comment]
[pythonProgramList.zip](https://github.com/uf-mil/NaviGator/files/1525286/pythonProgramList.zip)

**Comment by brooksturtle** [comment]
This should work, everything is in the readme

**Comment by brooksturtle** [comment]
Combined a bash and python file, let me know if it works for you

**Comment by ironmig** [comment]
Cool....  a little over complicated though. I think this could just be one python script [os.walk](https://docs.python.org/2/library/os.html#os.walk). Please PR it to mil_tools when this is done (it should be generic to run in any directory).

**Comment by ironmig** [comment]
Merged
