### ISSUE TITLE
Display NaviGator over satellite imagery

### ISSUE THREAD

**Issue by ironmig** [uf-mil/NaviGator#290]
NaviGator has a GPS and absolute (earth fixed) orientation sensors, so it is possible to display NaviGator's current position (and potentially other detected objects) over satellite imagery from open street maps or w/e. Not only would it look really cool, but it would help understand where we are at test days / competition when we can't see NaviGator easily!

* Google if there is some  easy way to do this in ROS already with an rviz / rqt plugin
* Otherwise, research some options to roll this out ourselves (web app is okay)

**Comment by joshrudi** [comment]
Just an update on this.  It appears it IS possible to do this in ROS via "rviz".  I've been playing around with getting the testing environment running in a Linux VM on my Mac, with many roadblocks.  Will update when I make progress.

**Comment by ironmig** [comment]
Cool! You can always test on the "shuttle" computer in the Lab to test. Dual booting is also an option, you can find resources for this online

**Comment by ironmig** [comment]
@RustyBamboo found a way to do this

**Comment by joshrudi** [comment]
Great!  Kudos @RustyBamboo

**Comment by joshrudi** [comment]
Just for future reference, here's a link for the built-in ROS method.  http://wiki.ros.org/gpsd_viewer#Usage

**Comment by ironmig** [comment]
@thedpws updates?

**Comment by thedpws** [comment]
It's worked for all the bags I've tested, so I'm submitting it for PR! https://github.com/uf-mil/NaviGator/pull/434
