### ISSUE TITLE
Anti-LED scanning computer vision node

### ISSUE THREAD

**Issue by ironmig** [uf-mil/NaviGator#291]
The scan the code challenge requires us to determine the color of an LED panel. One of the difficulties of this is that the LED panel has a refresh rate which shows scanning lines in images instead of the solid colors our eyes see. Besides working on this from the camera side, it should be possible to process an image to reduce this affect. Here's my idea:
* have NaviGator stay still while looking at the LED panel
* capture several images
* use an algorithm to smear these images together in a given region. If a pixel is near black, use the non-black pixel from a nearby frame. This should produce a more solid color in this part of the image with the scanning lines
 
![yellow](https://user-images.githubusercontent.com/9502636/35130632-ee057c7e-fc8f-11e7-8c70-b5da21ff72bb.png)

**Comment by ironmig** [comment]
Progress update @gdutk007 ?

**Comment by gdutk007** [comment]
unfortunately haven't made much progress, had to stop working on the assignment couple weeks into the semester. If anyone else is interested in working on it you can feel free to reassign

**Comment by ironmig** [comment]
Seems like a histogram approach may be better, clossing
