### ISSUE TITLE
Install script does not check if git is in installed

### ISSUE THREAD

**Issue by ironmig** [uf-mil/Navigator#33]
Daniel just tried to use the install script from a brand new Ubuntu 14.04 install. We noticed that it does not install git. Might be nice to add this to the script so it can be run without installing anything else first

**Comment by mattlangford** [comment]
Check line 131 of the install script
That line looks like it installs git

**Comment by ironmig** [comment]
Isn't the package git-core not git?

http://git.661346.n2.nabble.com/git-core-vs-git-package-on-ubuntu-td7576083.html

**Comment by mattlangford** [comment]
To piggy-back off this - install script needs to install git-lfs as well in order to get models for the gazebo

**Comment by whispercoros** [comment]
I added git-lfs, it will be in my next PR
