### ISSUE TITLE
Simulator issue

### ISSUE THREAD

**Issue by viron11111** [uf-mil/Navigator#43]
When the simulator starts up, the challenges do not appear.  We are missing all of the challenges except for the boat.  Also, I cannot see land in the simulator.

**Comment by mattlangford** [comment]
I am also having this issue

**Comment by whispercoros** [comment]
I have been working on the simulator over the past few days and am planning on bundling everything I have together in a PR sometime this weekend.

**Comment by mattlangford** [comment]
Just be sure to use gitlfs for any models

**Comment by RustyBamboo** [comment]
Last time I loaded it there were buoys... Now I can't get them to load.

**Comment by tessbianchi** [comment]
Yeah that's a really good idea!

**Comment by ironmig** [comment]
It would be very helpful to have some dock signs up there with different colors and shapes

**Comment by viron11111** [comment]
Did you bundle everything into a PR this weekend?

**Comment by LucasBA** [comment]
> 

> ``

**Comment by LucasBA** [comment]
It seems like the boat model is breaking the sim. getting [gazebo-18] process has died

**Comment by mattlangford** [comment]
Were you able to run it without the boat model?

**Comment by LucasBA** [comment]
Yes

**Comment by mattlangford** [comment]
Can you try to open the model in blender?

**Comment by LucasBA** [comment]
Ill try when I get back to the lab

**Comment by whispercoros** [comment]
The install script will automatically default to mil_ws/ now, but you can keep navigator_ws/ if you want by passing it with this:

./install.sh -c navigator_ws/

In #49, I added git-lfs installation and pull to the install script, so this should take care of any of those issues.

**Comment by whispercoros** [comment]
I have been working on a system that automatically generates the courses based on the specifications provided in the competition rules. Since this is taking longer than expected, I am just going to make a sandbox with all course elements in it by hand for the time being.

**Comment by tessbianchi** [comment]
Make sure that you run roslaunch navigator_launch simulation.launch, and don't directly run the goose.launch file. Should we mark as resolved?

**Comment by mattlangford** [comment]
So make sure you've `git lfs pull` so hat you have the most recent models, then like Tess said do `roslaunch navigator_launch simulation.launch`

**Comment by mattlangford** [comment]
We need challenges in the sim.

**Comment by DSsoto** [comment]
Anthony, it would be really useful we could have the challenges in the simulator.  Please add the challenges to the simulator.

**Comment by viron11111** [comment]
Don't worry guys.  Anthony told me he would have them finished by last night.  He's probably done with it and only needs to upload the updated files to Git.

**Comment by whispercoros** [comment]
I have most of the challenges ready in the sim, but Git-LFS keeps giving me errors when I attempt to pull and push from my local copy the repository. I am doing some research, but I will be in MIL tomorrow to see if anyone else has had similar issues.

**Comment by tessbianchi** [comment]
Anthony....where are my challenges?

**Comment by ironmig** [comment]
@whispercoros Have there been any updates on this? Are we going to bring the simulator changes into the main repo with a PR soon?

**Comment by whispercoros** [comment]
@ironmig Since I still need Lucas to model a few components, I will split this up into two PRs. I will merge your changes into the sandbox and open a PR to dev today.

**Comment by viron11111** [comment]
@whispercoros have you received the model from Lucas yet?

**Comment by whispercoros** [comment]
@viron11111, I received the models and have Detect and Deliver implemented in the simulator. It will be included in #83, which should be merged to dev on Saturday (10/22)

**Comment by viron11111** [comment]
Roger.

**Comment by whispercoros** [comment]
This has been fixed by #83
