### ISSUE TITLE
Thrusters not giving feedback

### ISSUE THREAD

**Issue by mattlangford** [uf-mil/Navigator#45]
Not sure if it's a hardware, firmware, or software issue. The thrusters won't return feedback information (we mainly just want battery voltage)

**Comment by whispercoros** [comment]
Any progress on this? It's not vital, but it would be nice to have a voltage indicator for testing.

**Comment by mattlangford** [comment]
Thrusters only fail to give feedback when launched from `master_boat.launch`. When launched by themselves everything seems to be fine.

**Comment by mattlangford** [comment]
The problem here is that if the motor drivers start up after the thruster mapper starts up, the motor driver seems to not ever poll for feedback from the thrusters. Solution for now is to sleep before the thruster mapper comes up so that the feedback polling will still continue. Fixing this would require some personal time with the roboteq thruster drivers.
