### ISSUE TITLE
Camera(s) do not use calibration file when launched

### ISSUE THREAD

**Issue by ironmig** [uf-mil/Navigator#84]
The camera launch files are configured to use a yaml file with the calibration found in the repo, but I've only observed zeroed out camerainfo messages and no rectified image available.

**Comment by mattlangford** [comment]
For which cameras?

**Comment by ironmig** [comment]
I know this is the case for the right camera, not sure about any others. Ralph is aware of this and said he'd look into it before Saturday

**Comment by ironmig** [comment]
Fix on lakeday 10/15/2016. Thanks ralph!
