### ISSUE TITLE
Side camera (for shooter) has unreliable auto whitebalance/exposure/brightness

### ISSUE THREAD

**Issue by ironmig** [uf-mil/Navigator#89]
The pointgrey camera on the right side of navigator, under the shooter, is unreliable in the auto configuration as compared to the front cameras, which look quite good at any of the tested conditions. This could be for a few reasons:
- The camera is physically in a tube which blocks a significant portion of its field of view the border of which is white. This could throw off the auto white balance or other settings.
- The settings on the camera/driver need to be tuned more

**Comment by ironmig** [comment]
Note: this problem greatly affects the reliability of the detect deliver symbol perception

**Comment by ironmig** [comment]
Another idea discussed is the set the ROI of the camera driver to ignore the borders of the waterproofing tube. Will this change what data is used for auto white balance?

**Comment by mattlangford** [comment]
Hopefully the new lens will fix this - manually setting certain camera settings doesn't really solve anything (as we saw) since looking at objects from different angles changes the light in the scene drastically.

**Comment by viron11111** [comment]
I still have the old lens if we need to go back.

**Comment by ironmig** [comment]
Seems to be significantly improved with new camera + lens. Will be even better with downward angled mount.
