### ISSUE TITLE
Object classifcation database should return the original data (Buoy.msg)

### ISSUE THREAD

**Issue by ironmig** [uf-mil/Navigator#90]
Currently, a service call to /database/single or /database/full returns data in the format of PerceptionObject.msg, which contains the objects id, name, size, and position. This removes some of the data of the original Buoy.msg sent by object detection, such as a normal and the 3D points of the object. For use in missions and for less confusion, perhaps this should just be one message format?

**Comment by mattlangford** [comment]
I think the plan right now is for @maverick7170 (Ira) to get a database full of automatically classified objects for this weekend. I'm going to assign him on this too - make sure he knows if you want more information in the message then what currently exists.

**Comment by maverick7170** [comment]
Yes, I'll have this ready for this weekend!
