### ISSUE TITLE
TF stereo messed up

### ISSUE THREAD

**Issue by tessbianchi** [uf-mil/Navigator#95]
![hey](https://cloud.githubusercontent.com/assets/7075487/19559326/4367f41c-969d-11e6-97d5-62c51466bea0.png)

This is what stereo TF looks like right now. It looks like one stereo is right in front of the other.

I don't think this is intended. @DSsoto  Is there a reason for this change?

**Comment by viron11111** [comment]
The right camera looks messed up too.  Needs to be rotated -90 about 
Y-Axis then +180 about Z-Axis.

**Comment by DSsoto** [comment]
Shame be upon my family. I calibrated the best TF I could but used degrees instead of radians when getting the orientation quaternion. Has since been fixed.
