### ISSUE TITLE
Lidar Classification

### ISSUE THREAD

**Issue by maverick7170** [uf-mil/Navigator#96]
Everyone,

 We should clarify who is doing what concercing lidar classification! After our Monday meeting, my goal was to take Tess's work and merge it back into my C++ code to have 1 node handling creating the ogrid, identifying objects, volume classification, and answering service requests. This information can then be used by other nodes for various purposes!

Essentially, I wanted to try free time up for Tess and also bundle the lidar code into 1 place. This way you can yell at me for any problems/errors/mistakes.

Tess you mentioned concerns about loosing functionality but I've already got your python code converted to C++ for remembering object ids and answering service requests.

Thoughts/comments/concerns? 

-Ira

**Comment by tessbianchi** [comment]
Sounds good to me! 

Thanks for this!

It would be nice if you could get color in the somehow get color data in there. I know @DSOTO has some code for this in navigator_perception. 

Once you push I will test it on some bags I have just to verify. Let me know when you are ready to merge.
